/// Phase 6 — MetadataEncoder.
///
/// Encodes OnLoginMetadata back to a minimal on-login prefix string.
/// Used for round-trip validation: metadata → encode → script → parse → metadata.
///
/// The full on-login string is generated by OnLoginScriptGenerator.
/// MetadataEncoder is used only for extracting and validating the
/// comma-position header portion of the script.
library;

import '../models/profile_models.dart';

/// Encodes metadata to and extracts the :put header from on-login scripts.
class MetadataEncoder {
  const MetadataEncoder();

  /// Encodes OnLoginMetadata to the comma-delimited header string embedded
  /// inside the :put ("...") statement.
  ///
  /// This is NOT the full on-login script — use OnLoginScriptGenerator for that.
  /// This produces only the metadata portion for round-trip validation.
  ///
  /// Format: "," + modeToken + "," + price + "," + validity + "," + sprice + ",," + lockToken + ","
  String encodeHeader(OnLoginMetadata meta, {String validity = ''}) {
    if (meta.mode == ExpiryMode.none && (meta.price == '0' || meta.price.isEmpty)) {
      // Empty on-login for none+no-price
      return '';
    }
    if (meta.mode == ExpiryMode.none) {
      // None with price: ",," + price + ",,,noexp," + lockToken + ","
      return ',,${meta.price},,,noexp,${meta.lockToken},';
    }

    final modeToken = meta.mode.token;
    return ',$modeToken,${meta.price},$validity,${meta.sellingPrice},,${meta.lockToken},';
  }

  /// Extracts just the :put header content from a full on-login script string.
  ///
  /// Returns null if the script does not contain a :put header.
  String? extractPutHeader(String onLogin) {
    if (onLogin.isEmpty) return null;
    // The :put statement always starts the script.
    // It may end with '");' (expiry modes) or '")'  (none+price mode).
    final start = onLogin.indexOf('("');
    if (start == -1) return null;
    // Look for '");' first, then fall back to '")'
    var end = onLogin.indexOf('");', start);
    if (end == -1) {
      end = onLogin.indexOf('")', start);
    }
    if (end == -1 || end <= start) return null;
    return onLogin.substring(start + 2, end);
  }

  /// Validates that the on-login script has the correct comma-position
  /// structure required by Mikhmon.
  ///
  /// Returns true when the header has ≥7 comma-delimited positions.
  bool hasValidPositions(String onLogin) {
    if (onLogin.isEmpty) return true; // empty is valid for none+no-price
    final header = extractPutHeader(onLogin);
    if (header == null) return false;
    return header.split(',').length >= 7;
  }
}
