/// Drift database table for router metadata.
///
/// IMPORTANT: credentials (password) are NEVER stored here.
/// Password lives in flutter_secure_storage only.
library;

import 'package:drift/drift.dart';

/// Drift table definition for stored routers.
class RouterTable extends Table {
  /// UUID primary key — generated by the app.
  TextColumn get id => text()();

  /// Human-readable display name.
  TextColumn get name => text().withLength(min: 1, max: 128)();

  /// IP address or hostname.
  TextColumn get host => text().withLength(min: 1, max: 256)();

  /// RouterOS API port.
  IntColumn get port => integer().withDefault(const Constant(8728))();

  /// API username.
  TextColumn get username => text().withLength(min: 1, max: 128)();

  /// Group/tag enum name.
  TextColumn get groupName =>
      text().withDefault(const Constant('ungrouped'))();

  /// Optional note.
  TextColumn get note => text().nullable()();

  /// Last time this router was selected/used (Unix ms).
  IntColumn get lastUsedAt => integer().nullable()();

  /// Creation timestamp (Unix ms).
  IntColumn get createdAt => integer().nullable()();

  @override
  Set<Column<Object>> get primaryKey => {id};
}
