/// Drift table for voucher batch metadata — Phase 5.
///
/// Stores the last/all generated batches for recovery and history.
/// Voucher passwords are the product being generated (not router admin passwords).
library;

import 'package:drift/drift.dart';

/// Drift table definition for voucher batches.
class VoucherBatchTable extends Table {
  /// UUID primary key — generated by the app.
  TextColumn get id => text()();

  /// Router id this batch belongs to.
  TextColumn get routerId => text()();

  /// Human-readable batch code (e.g. "vc-A7F2-20260726").
  TextColumn get batchCode => text()();

  /// Profile name used for generation.
  TextColumn get profileName => text()();

  /// Number of vouchers generated.
  IntColumn get quantity => integer()();

  /// Generation mode: 'voucher' (user=pass) or 'userpass' (separate).
  TextColumn get mode => text()();

  /// Character set enum name.
  TextColumn get charSet => text()();

  /// Username prefix (may be empty string).
  TextColumn get prefix => text().withDefault(const Constant(''))();

  /// Username length.
  IntColumn get usernameLength => integer()();

  /// Password length.
  IntColumn get passwordLength => integer()();

  /// Limit-uptime string (nullable — e.g. "1h", "1d").
  TextColumn get limitUptime => text().nullable()();

  /// Comment for the batch (nullable).
  TextColumn get comment => text().nullable()();

  /// Generation timestamp (Unix ms).
  IntColumn get generatedAt => integer()();

  /// JSON array of {name, password} objects — local only.
  /// Voucher passwords are the product being generated.
  TextColumn get voucherListJson => text()();

  @override
  Set<Column<Object>> get primaryKey => {id};
}
