# analysis_options.yaml — voucher_sdk
include: package:lints/recommended.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    unused_import: warning
    unused_local_variable: warning
  exclude:
    - "**/*.g.dart"
    - "build/**"

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_print: true
    camel_case_types: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_const: true
    unnecessary_new: true
